{{ if and (not .Values.db.external) .Values.k8s.persistence.enabled (eq .Values.db.type "db2")}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-db2-pvc
  labels:
spec:
{{- if not .Values.k8s.persistence.hasDefaultStorageClass }}
  storageClassName: {{ .Values.k8s.persistence.explicitStorageClass }}
{{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.db.persistence.size }}
{{ end }}