{{ if and ( not .Values.s3.external )  false }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-minio-secret
data:
  AWS_ACCESS_KEY_ID: "{{- .Values.s3.auth.username -}}"
  AWS_SECRET_ACCESS_KEY: "{{- .Values.s3.auth.password -}}"
  ENDPOINT: "http://{{- .Release.Name -}}-minio:{{- .Values.s3.port -}}"
{{ end }}
