{{ if and (not .Values.db.external) (eq .Values.db.type "postgres") }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-postgres
  labels:
    name: {{ .Release.Name }}-postgres
spec:
  replicas: {{ .Values.db.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-postgres
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-postgres
    spec:
      restartPolicy: {{ .Values.db.restartPolicy }}
      containers:
      - name: postgres
        image: "{{- .Values.docker.registry.name -}}{{- .Values.db.imageName -}}:{{- .Values.db.imageTag -}}"
        ports:
        - name: postgres
          containerPort: {{ .Values.db.port }}
        env:
        - name: "POSTGRES_USER"
          value: {{ .Values.db.auth.username }}
        - name: "POSTGRES_PASSWORD"
          value: {{ .Values.db.auth.password }}
        - name: "POSTGRES_DB"
          value: {{ .Values.db.name }}
      {{- if .Values.k8s.persistence.enabled }}
        volumeMounts:
        - name: database-storage
          mountPath: /var/lib/postgresql/data
      volumes:
        - name: database-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-postgres-pvc
      {{- end }}
{{- end }}
