{{ if and (not .Values.rabbitmq.external) .Values.k8s.persistence.enabled}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-rabbitmq-pvc
  labels:
spec:
{{- if not .Values.k8s.persistence.hasDefaultStorageClass }}
  storageClassName: {{ .Values.k8s.persistence.explicitStorageClass }}
{{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.db.persistence.size }}
{{ end }}